/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank_Project;



import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Khululiwe
 */
public class BankAppGUI extends javax.swing.JFrame {

     Login hello=new Login();
    BankProjectDatabase Fnb=new BankProjectDatabase();
    private boolean passwordVisible = false;
    private boolean cPasswordVisible = false;
    private DefaultTableModel tableModel;
    /**
     * Creates new form CreateAccount
     */
    public BankAppGUI() {
        initComponents();
        tableModel = (DefaultTableModel) transaction.getModel();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowOpened(WindowEvent e) {
                showAccount();
                returnTable();
                showBalance();
                showDepositBalance();
                showTransferBalance();
                Fnb.displayUsername(userNameSelectToTransferTo);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        newPin = new javax.swing.JButton();
        closeAccount = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        accountNumber = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        xswx = new javax.swing.JLabel();
        lastName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        bal = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        oldPin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        creationdate = new javax.swing.JLabel();
        update = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        withdrawAmount = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        balanceWithdraw = new javax.swing.JLabel();
        backWithdraw = new javax.swing.JButton();
        withdrawalAmount = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        depositAmountCash = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        balanceDeposit = new javax.swing.JLabel();
        backDeposit = new javax.swing.JButton();
        depositCash = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        transferAmountCash = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        balanceTransfer = new javax.swing.JLabel();
        backTransfer = new javax.swing.JButton();
        transferCash = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        userNameSelectToTransferTo = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transaction = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel1.setVerifyInputWhenFocusTarget(false);

        jPanel3.setBackground(new java.awt.Color(51, 204, 0));
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel3.setVerifyInputWhenFocusTarget(false);

        back.setBackground(new java.awt.Color(0, 102, 255));
        back.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        newPin.setBackground(new java.awt.Color(0, 102, 255));
        newPin.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        newPin.setForeground(new java.awt.Color(255, 255, 255));
        newPin.setText("Change Pin");
        newPin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newPinActionPerformed(evt);
            }
        });

        closeAccount.setBackground(new java.awt.Color(255, 0, 0));
        closeAccount.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        closeAccount.setForeground(new java.awt.Color(255, 255, 255));
        closeAccount.setText("Close Account");
        closeAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeAccountActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel1.setText("Account");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("AccountNumber");

        accountNumber.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        accountNumber.setText("accountNumber");

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel3.setText("FirstName");

        xswx.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        xswx.setText("LastName");

        jLabel4.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel4.setText("Balance");

        bal.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        bal.setText("Balance");

        jLabel6.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel6.setText("Pin/Password");

        oldPin.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        oldPin.setText("Pin");

        jLabel8.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel8.setText("CreationDate");

        creationdate.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        creationdate.setText("0000/00/00");

        update.setBackground(new java.awt.Color(204, 0, 204));
        update.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        update.setForeground(new java.awt.Color(255, 255, 255));
        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel9.setText("UserName");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(back)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 347, Short.MAX_VALUE)
                .addComponent(closeAccount)
                .addGap(48, 48, 48))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(xswx)
                            .addComponent(jLabel4)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(accountNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(firstName)
                            .addComponent(lastName, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                            .addComponent(bal)
                            .addComponent(userName)))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(newPin)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(update, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(creationdate))
                                    .addComponent(oldPin))))))
                .addGap(0, 53, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(200, 200, 200))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(accountNumber))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(xswx)
                    .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(bal))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(oldPin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(creationdate))
                .addGap(18, 18, 18)
                .addComponent(update, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 200, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newPin, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeAccount, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Account", jPanel2);

        jPanel5.setBackground(new java.awt.Color(51, 204, 0));
        jPanel5.setAutoscrolls(true);
        jPanel5.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel5.setVerifyInputWhenFocusTarget(false);

        withdrawAmount.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel5.setText("Balance");

        balanceWithdraw.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        balanceWithdraw.setText("P0.00");

        backWithdraw.setBackground(new java.awt.Color(0, 102, 255));
        backWithdraw.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        backWithdraw.setForeground(new java.awt.Color(255, 255, 255));
        backWithdraw.setText("Back");
        backWithdraw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backWithdrawActionPerformed(evt);
            }
        });

        withdrawalAmount.setBackground(new java.awt.Color(204, 0, 204));
        withdrawalAmount.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        withdrawalAmount.setForeground(new java.awt.Color(255, 255, 255));
        withdrawalAmount.setText("WithDraw");
        withdrawalAmount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withdrawalAmountActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel13.setText("Withdraw Cash");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(balanceWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(backWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(withdrawalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLabel13)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel13)
                .addGap(49, 49, 49)
                .addComponent(withdrawAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceWithdraw, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backWithdraw, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(withdrawalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(311, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Withdraw", jPanel4);

        jPanel7.setBackground(new java.awt.Color(51, 204, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel7.setVerifyInputWhenFocusTarget(false);

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel7.setText("Balance");

        balanceDeposit.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        balanceDeposit.setText("P0.00");

        backDeposit.setBackground(new java.awt.Color(0, 102, 255));
        backDeposit.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        backDeposit.setText("Back");
        backDeposit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDepositActionPerformed(evt);
            }
        });

        depositCash.setBackground(new java.awt.Color(204, 0, 204));
        depositCash.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        depositCash.setForeground(new java.awt.Color(255, 255, 255));
        depositCash.setText("Deposit");
        depositCash.setToolTipText("");
        depositCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositCashActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel14.setText("Deposit Cash");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(depositAmountCash, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(balanceDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(backDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(depositCash, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(jLabel14)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jLabel14)
                .addGap(55, 55, 55)
                .addComponent(depositAmountCash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceDeposit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backDeposit, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(depositCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(303, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Deposit", jPanel6);

        jPanel9.setBackground(new java.awt.Color(51, 204, 0));
        jPanel9.setPreferredSize(new java.awt.Dimension(600, 700));
        jPanel9.setVerifyInputWhenFocusTarget(false);

        transferAmountCash.setFont(new java.awt.Font("Viner Hand ITC", 0, 14)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel10.setText("Balance");

        balanceTransfer.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        balanceTransfer.setText("P0.00");

        backTransfer.setBackground(new java.awt.Color(0, 102, 255));
        backTransfer.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        backTransfer.setText("Back");
        backTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backTransferActionPerformed(evt);
            }
        });

        transferCash.setBackground(new java.awt.Color(204, 0, 204));
        transferCash.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        transferCash.setForeground(new java.awt.Color(255, 255, 255));
        transferCash.setText("Transfer");
        transferCash.setToolTipText("");
        transferCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferCashActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel11.setText("Amount");

        jLabel12.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel12.setText("Receipeint Username");

        userNameSelectToTransferTo.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        userNameSelectToTransferTo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Username" }));
        userNameSelectToTransferTo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameSelectToTransferToActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel15.setText("Transfer");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(transferAmountCash, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(balanceTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel9Layout.createSequentialGroup()
                                .addComponent(backTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(transferCash, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(userNameSelectToTransferTo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(212, 212, 212)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(61, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(transferAmountCash, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userNameSelectToTransferTo, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(balanceTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(backTransfer, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(transferCash, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(307, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        jTabbedPane1.addTab("Transfer", jPanel8);

        transaction.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        transaction.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "TransactionId", "TransactionName", "Amount", "Date", "Time"
            }
        ));
        jScrollPane1.setViewportView(transaction);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Transaction", jPanel10);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:

        Login dashboard = new Login(); 
                   dashboard.setVisible(true);
                    this.dispose();
    }//GEN-LAST:event_backActionPerformed

    private void newPinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newPinActionPerformed

        String oldpin = JOptionPane.showInputDialog(null, "Please enter your old Pin:", "Input Dialog", JOptionPane.PLAIN_MESSAGE);

        if(oldpin.equals(oldPin.getText().toString()))
        {
            String userInput = JOptionPane.showInputDialog(null, "Please enter your new Pin:", "Input Dialog", JOptionPane.PLAIN_MESSAGE);

            if (userInput != null) {

                Fnb.changePin(hello.getAccNummber(), userInput);
                JOptionPane.showMessageDialog(null, "Pin Changed ", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
           
            Login dashboard = new Login(); 
                   dashboard.setVisible(true);
                    this.dispose();
            } else {

                JOptionPane.showMessageDialog(null, "Pin change Cancelled.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
            }

        }else
        {
            JOptionPane.showMessageDialog(null, "Pin change Cancelled.", "Confirmation", JOptionPane.INFORMATION_MESSAGE);
        }
        // TODO add your handling code here:

    }//GEN-LAST:event_newPinActionPerformed

    private void closeAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeAccountActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "Sure you want to close your account", "Close Accoung",
            JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
        if (result == JOptionPane.YES_OPTION) {
            Fnb.deleteAccount(hello.getAccNummber());
            CreateAccount newOne=new CreateAccount();
            newOne.setVisible(true);
            this.dispose();

        } else {

        }
    }//GEN-LAST:event_closeAccountActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:

        String user=userName.getText().toString();
        String first=firstName.getText().toString();
        String last=lastName.getText().toString();

        if(user.isEmpty() ||first.isEmpty() || last.isEmpty())
        {

        }else
        {
            int result = JOptionPane.showConfirmDialog(null, "Sure you want to update your data", "Update",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION)
            {
                Fnb.profileUpdate(hello.getAccNummber(), user, first, last);
                 Login dashboard = new Login(); 
                   dashboard.setVisible(true);
                    this.dispose();
            }else
            {
                JOptionPane.showMessageDialog(null, "Could not update profile",
                    "Error", JOptionPane.ERROR_MESSAGE);
            }

        }

    }//GEN-LAST:event_updateActionPerformed

    private void backWithdrawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backWithdrawActionPerformed

        Login dashboard = new Login(); 
                   dashboard.setVisible(true);
                    this.dispose();      // TODO add your handling code here:
    }//GEN-LAST:event_backWithdrawActionPerformed

    private void withdrawalAmountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withdrawalAmountActionPerformed
        // TODO add your handling code here:
        String amount=withdrawAmount.getText().toString();
        if (amount.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please write withdrawal amount",
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            double x=Double.parseDouble(amount);

            int result = JOptionPane.showConfirmDialog(null, "Sure you want to withdraw", "WithDraw",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {

                Fnb.withdrawMoney(x,hello.getAccNummber());
                BankAppGUI Fnb=new BankAppGUI();
                Fnb.setVisible(true);
                this.dispose();

            } else {
                // Handle the case when the user chooses not to save data
            }}

    }//GEN-LAST:event_withdrawalAmountActionPerformed

    private void backDepositActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDepositActionPerformed
        BankAppGUI Fnb=new BankAppGUI();
        Fnb.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_backDepositActionPerformed

    private void depositCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositCashActionPerformed
        // TODO add your handling code here:
        String amount=depositAmountCash.getText().toString();
        if (amount.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please write deposit amount",
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            double x=Double.parseDouble(amount);

            int result = JOptionPane.showConfirmDialog(null, "Sure you want to Deposit", "Deposit",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {

                Fnb.depositCash(x,hello.getAccNummber());
                BankAppGUI Fnb=new BankAppGUI();
                Fnb.setVisible(true);
                this.dispose();

            } else {
                // Handle the case when the user chooses not to save data
            }}

    }//GEN-LAST:event_depositCashActionPerformed

    private void backTransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backTransferActionPerformed
        BankAppGUI Fnb=new BankAppGUI();
        Fnb.setVisible(true);
        this.dispose();           // TODO add your handling code here:
    }//GEN-LAST:event_backTransferActionPerformed

    private void transferCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferCashActionPerformed
        // TODO add your handling code here:
        String amount=transferAmountCash.getText().toString();
        String username=userNameSelectToTransferTo.getSelectedItem().toString();
        int id=Fnb.getAccountId(username);
        if (amount.isEmpty() ) {
            JOptionPane.showMessageDialog(null, "Please write transfer amount",
                "Error", JOptionPane.ERROR_MESSAGE);
        }else{
            double x=Double.parseDouble(amount);

            int result = JOptionPane.showConfirmDialog(null, "Sure you want to transfer", "Deposit",
                JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if(hello.getAccNummber()==id)
                {
                    JOptionPane.showMessageDialog(null, "Cannot send money to yourself",
                        "Error", JOptionPane.ERROR_MESSAGE);

                }else{
                    
                     double currentBalance = Double.valueOf(balanceTransfer.getText());
                if (currentBalance < x) {
                    JOptionPane.showMessageDialog(null, "Insufficient balance to make the transfer", "Error", JOptionPane.ERROR_MESSAGE);
                }else{
                    Fnb.bankTransfer(hello.getAccNummber(), id, x);
                    BankAppGUI Fnb=new BankAppGUI();
                    Fnb.setVisible(true);
                    this.dispose();
                }
                }

            } else {
                // Handle the case when the user chooses not to save data
            }}

    }//GEN-LAST:event_transferCashActionPerformed

    private void userNameSelectToTransferToActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameSelectToTransferToActionPerformed

        Fnb.displayUsername(userNameSelectToTransferTo);

        // TODO add your handling code here:

    }//GEN-LAST:event_userNameSelectToTransferToActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankAppGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankAppGUI().setVisible(true);
            }
        });
    }
    
    
     public void showBalance()
    {
        Fnb.setBalance(hello.getAccNummber(), balanceWithdraw);
    }
     public void showDepositBalance()
    {
        Login hello=new Login();
        Fnb.setBalance(hello.getAccNummber(), balanceDeposit);
    }
     public void showTransferBalance()
    {
        Fnb.setBalance(hello.getAccNummber(), balanceTransfer);
    }
     
     public void returnTable() {
        Fnb.transactions(hello.getAccNummber(), tableModel); // You may need to replace '1' with the actual account number.
    }
      public void showAccount()
    {
         try {
            // TODO add your handling code here:
            Connection con = null;
            con = DriverManager.getConnection("jdbc:mysql://localhost:4306/bankproject", "root", "");
            PreparedStatement os = con.prepareStatement("select accountnumber,username,holderfirstname,holderlastname,balance,pin,creationdate from bankaccounts where accountnumber=?");
            os.setInt(1, hello.getAccNummber());
            ResultSet res = os.executeQuery();

            if (res.next()) {
                accountNumber.setText(res.getString("accountnumber"));
                userName.setText(res.getString("username"));
                firstName.setText(res.getString("holderfirstname"));
                lastName.setText(res.getString("holderlastname"));
                bal.setText(res.getString("balance"));
                oldPin.setText(res.getString("pin"));
                creationdate.setText(res.getString("creationdate"));
                        }
        } catch (SQLException ex) {
            Logger.getLogger(BankAppGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel accountNumber;
    private javax.swing.JButton back;
    private javax.swing.JButton backDeposit;
    private javax.swing.JButton backTransfer;
    private javax.swing.JButton backWithdraw;
    private javax.swing.JLabel bal;
    private javax.swing.JLabel balanceDeposit;
    private javax.swing.JLabel balanceTransfer;
    private javax.swing.JLabel balanceWithdraw;
    private javax.swing.JButton closeAccount;
    private javax.swing.JLabel creationdate;
    private javax.swing.JTextField depositAmountCash;
    private javax.swing.JButton depositCash;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastName;
    private javax.swing.JButton newPin;
    private javax.swing.JLabel oldPin;
    private javax.swing.JTable transaction;
    private javax.swing.JTextField transferAmountCash;
    private javax.swing.JButton transferCash;
    private javax.swing.JButton update;
    private javax.swing.JTextField userName;
    private javax.swing.JComboBox<String> userNameSelectToTransferTo;
    private javax.swing.JTextField withdrawAmount;
    private javax.swing.JButton withdrawalAmount;
    private javax.swing.JLabel xswx;
    // End of variables declaration//GEN-END:variables
}
