/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank_Project;

import javax.swing.JOptionPane;

/**
 *
 * @author Khululiwe
 */
public class CreateAccount extends javax.swing.JFrame {

    
    BankProjectDatabase Fnb=new BankProjectDatabase();
    private boolean passwordVisible = false;
    private boolean cPasswordVisible = false;
    /**
     * Creates new form CreateAccount
     */
    public CreateAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        userName = new javax.swing.JTextField();
        firstName = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        balance = new javax.swing.JTextField();
        pin = new javax.swing.JPasswordField();
        TogglePin = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        accountCreate = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cPin = new javax.swing.JPasswordField();
        cTogglePin = new javax.swing.JRadioButton();
        LoginHere = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(600, 700));
        jPanel1.setPreferredSize(new java.awt.Dimension(600, 700));

        userName.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pin.setText("0000");
        pin.setOpaque(true);
        pin.setPreferredSize(new java.awt.Dimension(70, 22));

        TogglePin.setText("Show");
        TogglePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogglePinActionPerformed(evt);
            }
        });

        jLabel1.setText("FIRSTNAME");

        jLabel2.setText("ACCOUNT HOLDER NAME");

        jLabel3.setText("LASTNAME");

        jLabel4.setText("INITIAL BALANCE");

        cancel.setBackground(new java.awt.Color(204, 0, 204));
        cancel.setForeground(new java.awt.Color(255, 255, 255));
        cancel.setText("Cancel");
        cancel.setToolTipText("");

        accountCreate.setBackground(new java.awt.Color(204, 0, 204));
        accountCreate.setText("Create Account");
        accountCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountCreateActionPerformed(evt);
            }
        });

        jLabel5.setText("PIN");

        cPin.setText("0000");

        cTogglePin.setText("show");
        cTogglePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cTogglePinActionPerformed(evt);
            }
        });

        LoginHere.setBackground(new java.awt.Color(255, 255, 153));
        LoginHere.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        LoginHere.setText("Already have Account? Login here");
        LoginHere.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginHereActionPerformed(evt);
            }
        });

        jLabel6.setText("Confirm Pin");

        jLabel7.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel7.setText("SIGN UP");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(cPin, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TogglePin))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGap(350, 350, 350)
                                    .addComponent(cTogglePin)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(userName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                                .addComponent(firstName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(balance, javax.swing.GroupLayout.Alignment.LEADING))
                            .addComponent(jLabel6)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(accountCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(LoginHere))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel7)))
                .addContainerGap(142, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel7)
                .addGap(31, 31, 31)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(balance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TogglePin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cPin, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cTogglePin))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(accountCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(LoginHere)
                .addGap(0, 53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 719, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TogglePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogglePinActionPerformed
        // TODO add your handling code here:
         passwordVisible = !passwordVisible;
        if (passwordVisible) {
            pin.setEchoChar((char) 0); // Show the password as plain text
             TogglePin.setText("Hide");
        } else {
            pin.setEchoChar('*'); // Hide the password with asterisks
           TogglePin.setText("Show");
        }
    }//GEN-LAST:event_TogglePinActionPerformed

    private void accountCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountCreateActionPerformed
        // TODO add your handling code here:
  String username = userName.getText().trim();
    String firstname = firstName.getText().trim();
    String lastname = lastName.getText().trim();
    String initialBalance = balance.getText().trim();
    String pinOne = pin.getText().trim();
    String pinTwo = cPin.getText().trim();

    if (username.isEmpty() || firstname.isEmpty() || lastname.isEmpty() || initialBalance.isEmpty() || pinOne.isEmpty() || pinTwo.isEmpty()) {
        JOptionPane.showMessageDialog(null, "All Fields should be filled", "Error", JOptionPane.ERROR_MESSAGE);
    } else if (!pinOne.equals(pinTwo)) {
        JOptionPane.showMessageDialog(null, "Pins do not match", "Error", JOptionPane.ERROR_MESSAGE);
    } else {
        double bal = Double.parseDouble(initialBalance);

        if (bal < 20.00) {
            JOptionPane.showMessageDialog(null, "Initial Balance can not be less than 20", "Error", JOptionPane.ERROR_MESSAGE);
        } else {
            int result = JOptionPane.showConfirmDialog(null, "Sure to save data?", "Create Account",
                    JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
            if (result == JOptionPane.YES_OPTION) {
                if (Fnb.accountCreation(username, firstname, lastname, bal, pinOne)) {
                   
                   Login dashboard = new Login(); 
                   dashboard.setVisible(true);
                    this.dispose();
                }
            } else {
                // Handle the case when the user chooses not to save data
            }
        }
    }
        
    }//GEN-LAST:event_accountCreateActionPerformed

    private void cTogglePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cTogglePinActionPerformed
        // TODO add your handling code here:
         cPasswordVisible = !cPasswordVisible;
        if (cPasswordVisible) {
            cPin.setEchoChar((char) 0); // Show the password as plain text
             cTogglePin.setText("Hide");
        } else {
            cPin.setEchoChar('*'); // Hide the password with asterisks
           cTogglePin.setText("Show");
        }
    }//GEN-LAST:event_cTogglePinActionPerformed

    private void LoginHereActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginHereActionPerformed

        // TODO add your handling code here:
        Login Fnb=new Login();
        Fnb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LoginHereActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginHere;
    private javax.swing.JRadioButton TogglePin;
    private javax.swing.JButton accountCreate;
    private javax.swing.JTextField balance;
    private javax.swing.JPasswordField cPin;
    private javax.swing.JRadioButton cTogglePin;
    private javax.swing.JButton cancel;
    private javax.swing.JTextField firstName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastName;
    private javax.swing.JPasswordField pin;
    private javax.swing.JTextField userName;
    // End of variables declaration//GEN-END:variables
}
