/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bank_Project;

import javax.swing.JOptionPane;

/**
 *
 * @author Khululiwe
 */
public class Login extends javax.swing.JFrame {

    
    BankProjectDatabase Fnb=new BankProjectDatabase();
    private boolean passwordVisible = false;
    private boolean cPasswordVisible = false;
    
    public static int accNummber=0;

    public int getAccNummber() {
        return accNummber;
    }

    public void setAccNummber(int accNummber) {
        this.accNummber = accNummber;
    }
    /**
     * Creates new form CreateAccount
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toCreate = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        username = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        login = new javax.swing.JButton();
        TogglePin = new javax.swing.JRadioButton();
        pin = new javax.swing.JPasswordField();
        createAcc = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Create Account");
        setBackground(new java.awt.Color(0, 51, 51));
        setResizable(false);

        toCreate.setBackground(new java.awt.Color(51, 204, 0));
        toCreate.setForeground(new java.awt.Color(255, 255, 255));
        toCreate.setFocusCycleRoot(true);
        toCreate.setPreferredSize(new java.awt.Dimension(600, 700));
        toCreate.setVerifyInputWhenFocusTarget(false);

        jLabel1.setFont(new java.awt.Font("Sitka Text", 0, 18)); // NOI18N
        jLabel1.setText("USERNAME");
        jLabel1.setFocusCycleRoot(true);

        username.setFocusCycleRoot(true);

        jLabel2.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jLabel2.setText("PIN");
        jLabel2.setFocusCycleRoot(true);

        login.setBackground(new java.awt.Color(204, 0, 204));
        login.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setText("Login");
        login.setFocusCycleRoot(true);
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        TogglePin.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        TogglePin.setText("Show");
        TogglePin.setFocusCycleRoot(true);
        TogglePin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TogglePinActionPerformed(evt);
            }
        });

        pin.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        pin.setFocusCycleRoot(true);

        createAcc.setBackground(new java.awt.Color(255, 255, 153));
        createAcc.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        createAcc.setText("Dont have Account? Create Account");
        createAcc.setFocusCycleRoot(true);
        createAcc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createAccActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Sitka Text", 0, 24)); // NOI18N
        jLabel3.setText("LOGIN");

        javax.swing.GroupLayout toCreateLayout = new javax.swing.GroupLayout(toCreate);
        toCreate.setLayout(toCreateLayout);
        toCreateLayout.setHorizontalGroup(
            toCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, toCreateLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
            .addGroup(toCreateLayout.createSequentialGroup()
                .addGroup(toCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(toCreateLayout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addGroup(toCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(createAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(login, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                            .addComponent(username)
                            .addGroup(toCreateLayout.createSequentialGroup()
                                .addGap(150, 150, 150)
                                .addComponent(jLabel2))
                            .addComponent(pin))
                        .addGap(18, 18, 18)
                        .addComponent(TogglePin))
                    .addGroup(toCreateLayout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(jLabel1)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        toCreateLayout.setVerticalGroup(
            toCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(toCreateLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(username, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(toCreateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pin, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TogglePin))
                .addGap(33, 33, 33)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(createAcc)
                .addContainerGap(190, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(toCreate, javax.swing.GroupLayout.PREFERRED_SIZE, 623, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(toCreate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TogglePinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TogglePinActionPerformed
        // TODO add your handling code here:
           passwordVisible = !passwordVisible;
        if (passwordVisible) {
            pin.setEchoChar((char) 0); // Show the password as plain text
             TogglePin.setText("Hide");
        } else {
            pin.setEchoChar('*'); // Hide the password with asterisks
           TogglePin.setText("Show");
        }
    }//GEN-LAST:event_TogglePinActionPerformed

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
        
        String userName=username.getText().toString();
        String p=pin.getText().toString();
        
        if(userName.isEmpty() || p.isEmpty())
        {
             JOptionPane.showMessageDialog(null, "One of the fields are empty",
                "Error", JOptionPane.ERROR_MESSAGE);
            
        }else{
            if(Fnb.loginToAccount(userName,p))
            {
                Login hello=new Login();
                hello.setAccNummber(Fnb.getAccountId(userName));
                
                BankAppGUI chain=new BankAppGUI();
                chain.setVisible(true);
                this.dispose(); 
                
            }else
            {
                JOptionPane.showMessageDialog(null, "Invalid inputs",
                "Error", JOptionPane.ERROR_MESSAGE);
                
            }
        }
        
        
        
        
    }//GEN-LAST:event_loginActionPerformed

    private void createAccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createAccActionPerformed
        // TODO add your handling code here:
        CreateAccount Fnb=new CreateAccount();
        Fnb.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_createAccActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton TogglePin;
    private javax.swing.JButton createAcc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField pin;
    private javax.swing.JPanel toCreate;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
